name: EtCetera
version: '${version}'
main: org.swlab.etcetera.EtCetera
api-version: '1.20'
commands:
  nbt검사:
  spawn:
    aliases: [ "로비", "넴주", "스폰", "lobby", "tmvhs", "ㅅㅍ", "tv" ]
  광산:
    aliases: [ "채광", "채광장", "rhkdtks", "corhkdwkd", "ㄳ", "ㄱㅅ" ]
  던전:
    aliases: [ "사냥", "사냥터", "ejswjs", "tksid", "tksidxj", "ㄷㅈ", "ew" ]
  쓰레기통:
    aliases: [ "쓰" ]
  장비:
    aliases: [ "장비창", "wkdql", "wkdqlckd", "acc", "ㅈㅂ", "wq" ]
  강화:
    aliases: [ "rkdghk", "ㄱㅎ", "rg" ]
  합성:
    aliases: [ "gkqtjd", "ㅎㅅ","gt" ]
  전리품:
    aliases: [ "wjsflvna", "전리품판매", "wjsflvnavksao", "상점", "상점가", "tkdwja", "tkdwjark", "후원상점", "캐시상점", "루비상점","fnqltkdwja", "zotltkdwja", "gndnjstkdwja" ]
  판도라:
    aliases: [ "vksehfk", "특수무기", "xmrtnanrl" ]
  스텟:
    aliases: [ "스탯", "tmxot", "tmxpt", "stat", "ㅅㅌ", "tx" ]
  직업:
    aliases: [ "직업변경", "클래스", "wlrdjq","zmffotm","wlrdjqqusrud" ]
  낚시:
    aliases: [ "skRtl", "skrtl", "낙시" ]
  기본템:
    aliases: [ "rlqhsxpa" ]
  퀘스트:
    aliases: [ "q", "ㅂ", "znptmxm" ]
  마을:
    aliases: [ "village", "akdmf", "빌리지", "ㅁㅇ", "ad" ]
  메뉴:
    aliases: [ "menu", "apsb" ]
  후원:
    aliases: [ "gndnjs" ]
  메일함:
    aliases: [ "apdlfgka" ]
  시장:
    aliases: [ "tlwkd","rudaowkd","경매장", "ㅅㅈ", "tw" ]
  디스코드:
    aliases: [ "eltmzhem", "elzh", "디코" ]
  엔더상자:
    aliases: [ "dpsejtkdwk" ]
  창고:
    aliases: [ "ckdrh", "ㅊㄱ", "cr" ]
  파티:
    aliases: [ "vkxl" ]
  루비:
    aliases: [ "zotl", "fnql" ]
  잠수:
    aliases: [ "wkatn" ]
  잠수포인트:
    aliases: [ "wkatnvhdlsxm" ]
  PVP:
    aliases: [ "피비피", "pk" ]
  음악:
    aliases: [ "dmadkr","qoruddmadkr","배경음악","노래","shfo" ]
  정보:
    aliases: [ "wjdqh" ]
  필드보스:
    aliases: [ "vlfemqhtm", "필보","qhtm","vlfqh","보스" ,"qt", "ㅄ", "ㅂㅅ" ]
  친구:
    aliases: [ "clsrn" ]
  쿠폰:
    aliases: [ "znvhs" ]
  펫:
    aliases: [ "vpt" ]
  엘븐하임:
    aliases: [ "dpfqmsgkdla", "엘븐" ]
  칼리마:
    aliases: [ "zkfflak" ]
  인페리움:
    aliases: [ "dlsvpfldna", "인페" ]
  아르크티카:
    aliases: [ "dkfmzmxlzk", "아르크" ]
  훈련장:
    aliases: [ "훈련", "gnsfuswkd", "gnsfus", "epalwlxptmxm", "데미지테스트" ]
  도움말:
    aliases: [ "ehdnaakf", "help", "헬프", "위키", "사이트", "dnlzl","tkdlxm","wiki","site","ghavpdlwl","홈페이지" ]
  아포칼립스:
    aliases: [ "dkvhzkfflqtm", "아포","dkvh" ]
  장사글:
    aliases: ["wkdtkrmf", "확성기", "ghkrtjdrl"]